//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DeskCharger.rc
//
#define IDS_ERRMSGCODE                  1
#define IDS_ERRMSGPOS                   2
#define IDS_MAINCDROM                   3
#define IDS_SAVE                        4
#define IDS_SET                         5
#define IDS_HOTKEYWARM                  6
#define IDS_TOOMANYCDROM                7
#define IDS_TOOLARGERVALUE              8
#define IDS_CDROMNOTSAVED               9
#define IDS_HOTCMDNOTSAVED              10
#define IDS_TIMINGNOTSAVED              11
#define IDS_PLEASESAVE                  12
#define IDS_NOTSAVED                    13
#define IDS_AUTOEJECT                   14
#define IDS_CDROMDEFAULT                15
#define IDS_DEFAULT                     16
#define IDS_SETINFO                     17
#define IDS_SAVEINFO                    18
#define IDS_CLOSEDLG                    19
#define IDS_NOCDROM                     20
#define IDS_UNABLEGETVER                21
#define IDS_REGERROR                    22
#define IDS_TRAYINFO                    23
#define IDS_TRAYINFOTITLE               24
#define IDS_MENUENABLE                  25
#define IDS_MENUOPTION                  26
#define IDS_MENUHELP                    27
#define IDS_MENUUNINST                  28
#define IDS_MENUEXIT                    29
#define IDS_TABCDROMSET                 30
#define IDS_TABHOTKEYSET                31
#define IDS_TABTIMINGSET                32
#define IDS_TABABOUT                    33
#define IDS_GETAPPNAMEERR               34
#define IDS_TIMING                      35
#define IDS_READINFO                    36
#define IDS_ADDINFO                     37
#define IDS_DELINFO                     38
#define IDS_EDITINFO                    39
#define IDS_LSTHOTKEYDEFINE             40
#define IDS_LSTHOTKEYENABLE             41
#define IDS_LSTHOTKEYFUNC               42
#define IDS_CONTROLPAD                  44
#define IDS_ADDREMOVEAPP                45
#define IDS_NOTEPAD                     46
#define IDS_MSDOSMODE                   47
#define IDS_CALCPAD                     48
#define IDS_IEEXPLORER                  49
#define IDS_SHUTDOWN                    50
#define IDS_RESTART                     51
#define IDS_LOGOFF                      52
#define IDS_SCREENSAVER                 53
#define IDS_WAITMODE                    54
#define IDS_SLEEPMODE                   55
#define IDS_UNABLEGETPATH               56
#define IDS_LSTENABLE                   57
#define IDS_LSTENABLECUROPTION          57
#define IDS_LSTDISABLE                  58
#define IDS_LSTDISABLECUROPTION         58
#define IDS_LSTALLOPTION                59
#define IDS_LSTCUROPTION                60
#define IDS_LSTLINKOPTION               61
#define IDS_LSTDELETE                   62
#define IDS_LSTDELETECUROPTION          62
#define IDS_LSTEDITCUR                  63
#define IDS_LSTADDNEW                   64
#define IDS_CMDMUSTINPUT                65
#define IDS_KEYCOMBINMUST               66
#define IDS_HOTKEYUSEF                  67
#define IDS_ADDNEW                      68
#define IDS_EDIT                        69
#define IDS_GETFILENAME                 70
#define IDS_OPENFILE                    71
#define IDS_ISDELCURINFO                72
#define IDS_ISDELALLINFO                73
#define IDS_TOOMANYHKI                  74
#define IDS_LSTTIME                     75
#define IDS_LSTDATE                     76
#define IDS_LSTOTHERTIMEINFO            77
#define IDS_UNISTINFO                   78
#define IDS_UNISTECHO                   79
#define IDS_UNISTREGECHO                80
#define IDS_EXECERR                     81
#define IDS_NOFILEDIRERR                82
#define IDS_MAILTOME                    83
#define IDD_DESKCHARGER_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDD_CDROM                       129
#define IDD_HOTKEY                      130
#define IDD_TIMER                       131
#define IDD_ABOUT                       132
#define IDI_TRAYNORMAL                  134
#define IDI_TRAYABNORMAL                136
#define IDR_TOOLBAR                     137
#define IDI_SETTING                     139
#define IDI_DEFAULT                     140
#define IDI_SAVE                        141
#define IDI_CDROMDEFAULT                142
#define IDI_CLOSEDLG                    143
#define IDI_DELINFO                     144
#define IDI_EDITINFO                    145
#define IDI_NEWINFO                     146
#define IDI_READINFO                    147
#define IDI_TIMING                      148
#define IDI_ENABLE                      150
#define IDI_DISABLE                     151
#define IDR_LSTTOOLBAR                  152
#define IDI_TRAYNORMALXP                157
#define IDI_TRAYABNORMALXP              158
#define IDD_HOTKEYADDEDIT               160
#define IDI_OPENFILE                    162
#define IDC_HANDURL                     163
#define IDD_SHUTDOWN                    164
#define IDI_SHUTDOWN                    165
#define IDI_RESTART                     166
#define IDT_CDROM                       255
#define IDT_ALLCDROM                    265
#define IDC_CLOSE                       1000
#define IDC_MAINTAB                     1001
#define IDC_CDROMLAB                    1002
#define IDC_CDROMSETHOTKEY              1003
#define IDC_SETCDROMHOTKEY              1004
#define IDC_SETCDROMDEFAULT             1005
#define IDC_SETDEFAULTCDROM             1006
#define IDC_AUTOCLOSE                   1007
#define IDC_AUTOEJECT                   1008
#define IDC_MAINCDROM                   1009
#define IDC_LAB                         1010
#define IDC_AUTORUN                     1011
#define IDC_TIMELIST                    1012
#define IDC_STARTTIME                   1016
#define IDC_ADDTIMENEW                  1017
#define IDC_READTIMEINFO                1018
#define IDC_HOTKEYLIST                  1019
#define IDC_DELTIMEINFO                 1020
#define IDC_SAVETIMEINFO                1021
#define IDC_EDITTIMEINFO                1022
#define IDC_SAVEHOTKEYINFO              1023
#define IDC_EDITHOTKEYINFO              1024
#define IDC_DELHOTKEYINFO               1025
#define IDC_ADDHOTKEYNEW                1026
#define IDC_READHOTKEYINFO              1027
#define IDC_COMBOKEYSELECT              1028
#define IDC_ADDEDIT                     1029
#define IDC_HTICMD                      1032
#define IDC_HTIPARM                     1033
#define IDC_HTIINFO                     1034
#define IDC_KEYCTRL                     1035
#define IDC_KEYALT                      1036
#define IDC_KEYSHIFT                    1037
#define IDC_LISTFILES                   1038
#define IDC_LISTFILES2                  1039
#define IDC_MAIL                        1040
#define IDC_TITLE                       1041
#define IDC_VERSION                     1042
#define IDC_DECLARE                     1043
#define IDC_RESTART                     1044
#define IDM_OPTION                      32771
#define IDM_HELP                        32772
#define IDM_UNINST                      32773
#define IDM_EXIT                        32774
#define IDM_ENABLE                      32776
#define IDM_LSTADDNEW                   32777
#define IDM_LSTEDIT                     32778
#define IDM_LSTDELCUR                   32779
#define IDM_LSTABLECUR                  32780
#define IDM_CLOSE                       0xF060

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1045
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
